# Generated by Django 3.0.7 on 2021-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepack', '0003_homemodel_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemodel',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='author',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
