# Generated by Django 3.0.7 on 2021-08-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepack', '0004_auto_20210807_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
